---
title: Robot maze
hero_image: images/banner.png
description: Make a robot maze game with the Unity development platform
version: 4.0.0
listed: true
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: unity
site_areas: coderdojo
software: unity
last_tested: '2018-07-12'
steps:
- title: Introduction
- title: Set the stage
- title: Make a robot
  completion:
  - engaged
- title: Add colour
- title: Make the world's ground
- title: Make MazeRobo move
- title: Moving properly
- title: Camera tracking
- title: Give MazeRobo something to play with
- title: Winning!
  completion:
  - internal
